### ISSUE TITLE
Loads only new likes not previous

### ISSUE THREAD

**Issue by ghost** [clarkwinkelmann/flarum-ext-likes-received#8]
Hi i use it on FreeFlarum, plugin version. 0.1.2. If i turn on, plugin not load actual likes,
The plugin simply reads the likes of it since it was turned on, not the previous likes.

Is possible make this plugin automatic read current status? For example, add to refresh button in to settings of this plugin ?

**Comment by clarkwinkelmann** [comment]
Hi!

As explained in the README, there's a command to run to update all counters:

    php flarum clarkwinkelmann:likes-received:refresh

Unfortunately you likely cannot run the command yourself on FreeFlarum since you won't have access to the command line.

I'm not planning to add any way to do this via the user interface for now because it's not something that has to be done regularly and it is usually performed by the forum owner who should usually have SSH access.

I think if you ask the FreeFlarum support they might be able to run the command for you.
